name: Build mysql-router container image
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker context for buildx
        run: |
          docker context create router-build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate image tag
        run: |
          echo 'IMG_TAG<<EOF' >> $GITHUB_OUTPUT
          for tag in $(bash tag.sh); do
            echo "type=raw,value=$tag" >> $GITHUB_OUTPUT;
          done
          echo "EOF" >> $GITHUB_OUTPUT
        id: img_tag
        working-directory: ./mysql-router

      - name: Set up docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/mysql-router
          tags: |
            ${{ steps.img_tag.outputs.IMG_TAG }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: router-build
          platforms: linux/amd64,linux/arm64

      - name: Build mysql-router
        uses: docker/build-push-action@v3
        with:
          context: mysql-router/8.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
